version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/var/www/html/
    ports:
      - 80:80
  db:
    image: mysql:latest
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: hicham
      MYSQL_DATABASE: dockerprojdb
    ports:
      - 5000:3306
  phpmya:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PASSWORD: hicham
    ports:
      - 8899:80